### PR TITLE
Issue 28 update onboarding pages

### PR DESCRIPTION
**Pull request by neilfulwiler**
see https://github.com/PlasticPatrol/PlasticPatrolWeb/issues/28

The background color has actually already been updated, this just uses the new images with the transparent background so the background color of the whole page makes sense.

I had 3 PNGs so I had to sort of position them a bit manually which seems error prone, @joe-mcguinness can we (or how should I) collapse them into a single PNG?

### CODE REVIEW

**Comment by joe-mcguinness** [comment]
seeItSnapItMapIt

I've attached a composite image here. Annoyingly the original images are all different sizes so it was a bit fiddly. Let me know if this image works or not.

**Comment by neilfulwiler** [comment]
Thanks @joe-mcguinness. Ok this is the before and after, it looks a bit like my first attempt at using the individual images, which seemed to result in the bottom two being a bit squished. Let me know if this is good though and I'm happy to go with it.

before:
Screen Shot 2020-04-21 at 8 13 29 PM

after:
Screen Shot 2020-04-21 at 8 12 06 PM

**Comment by neilfulwiler** [comment]
I manually shifted the middle image up by like 20px and it looked better, maybe we can do that with the composite too

**Comment by joe-mcguinness** [comment]
seeItSnapItMapIt
I've just rejigged the image here Neil, although it still doesn't have a great resolution on the onboarding screens you attached - I'll chase this down later

**Comment by neilfulwiler** [comment]
nice thanks @joe-mcguinness that looks great, and, and it does look higher def locally

Screen Shot 2020-04-22 at 7 34 42 PM

**Comment by neilfulwiler** [comment]
given that this is *just* a change to that PNG, just gonna merge it

**Pull request merged**
