### PR TITLE
enh/remove sponsor and update buttons

### PR DESCRIPTION
**Pull request by munroTom**
Removed sponsor logo, updated copy and added an extra button to the success dialog as requested by Liz

Screenshot 2021-04-20 at 07 36 12
Screenshot 2021-04-20 at 07 36 18
Screenshot 2021-04-20 at 07 43 52

### CODE REVIEW

**Review by joykuotw — CHANGES_REQUESTED** [review]
why the linter makes the imports single quoted? it is inconsistent.

**Comment by munroTom** [comment]
My bad, have a separate linter that sorts imports that I didn't realise was on / had different settings to this project

Have gone through + reformatted the files I touched

**Review by joykuotw — CHANGES_REQUESTED** [review]
Would it be better to not entirely remove all the sponsor related codes for future partnership? we can just hide the logo if there is no sponsor.

**Comment by joykuotw** [comment]
Close this PR. Instead of remove the sponsor codes. We just hide it if there is no sponsor yet. https://github.com/PlasticPatrol/PlasticPatrolWeb/pull/370

**Pull request closed without merging**
