### PR TITLE
fix csv function

### PR DESCRIPTION
**Pull request by munroTom**
Deployed to the dev environment to test and seems to be working now https://us-central1-plastic-patrol-dev-722eb.cloudfunctions.net/api/photos.csv

Didn't work after I first deployed it but I think there was a lag as it seems ok now

### CODE REVIEW

**Review by alastairdglennie — APPROVED** [review]

**Comment by neilfulwiler** [comment]
I think I still don't understand javascript import syntax, whats the actual change here?

**Comment by munroTom** [comment]
@neilfulwiler 
The change is instead of getting the default export and trying to read the `Parser` property off of it we're getting the named export `Parser` from it as well - I think another fix for it would have been to do `import * as json2csv`

As an example

```js
// myExports.js
export const namedExport1
export const namedExport2

// can only have one default export per file
export default {
     partOfDefault1,
     partOfDefault2
}

// separate file

import insertAliasHere from 'myExports' // gets the default only
import { namedExport1 } from 'myExports'
import * as otherAlias from 'myExports' // grabs everything 
const { namedExport1, namedExport2, default: defaultExport } = otherAlias
```

However this fix didn't work in prod so the issue still needs resolving - I don't know if we're reaching the limit of what we can send back in the headers?

**Comment by neilfulwiler** [comment]
if it didn't work in prod should we close this?

**Comment by lizheard1** [comment]
@munroTom @neilfulwiler I'm still getting the 'error: could not handle request' message? 
image

Unless I should be using a different API to access the data now?

**Comment by munroTom** [comment]
@lizheard1 this fix didn't end up solving the issue so it hasn't been merged (which is why we closed it), at some point some we'll hopefully be able to solve the problem but for now we were closing the pr to indicate the work wasn't in progress

I've taken a look into some other approaches and posted them in slack (I think in the dev channel) but for now I'm focussing more on getting work for the challenges feature done, if it's a priority I can pick this back up instead

**Pull request closed without merging**
