### PR TITLE
Bug fixes take 3

### PR DESCRIPTION
**Pull request by neilfulwiler**
* synonyms
* add crisp packets/sweets wrapper
* centralise plus/minus icons
* add list for scrolling through categories
* change plastic->planet patrol
* log->record your litter
* fixed gap between brand and category
* typescript some things

### CODE REVIEW

**Comment by munroTom** [comment]
Do we send the tags to the backend anywhere?

We used to only send the leafkeys which is part of the issue with "custom" categories

**Comment by neilfulwiler** [comment]
haha i KNEW there was something that I was forgetting. ok. just gonna send up the tag as well, not sure if we didn't before just as a data saving thing? seems like it should be fine to send up the whole thing

**Comment by munroTom** [comment]
Just merged develop as I'm guessing the only reason cypress failed was cause it doesn't exist on this branch yet

**Comment by munroTom** [comment]
closes: #73 
closes: #87 
closes: #89 
closes: #67 
closes: #72

**Pull request merged**
